### ISSUE TITLE
build error with maven 2.2.1

### ISSUE THREAD

**Issue by afaresse** [StratusLab/cimi#3]
[war:war {execution: default-war}]

> > > > > [INFO] Packaging webapp
> > > > > [INFO] Assembling webapp [cimi-war] in [/home/afaresse/Bureau/cimi-master/war/target/cimi-war-13.10.0-SNAPSHOT]
> > > > > [INFO] Processing war project
> > > > > [INFO] Copying webapp webResources [/home/afaresse/Bureau/cimi-master/war/src/main/war] to [/home/afaresse/Bureau/cimi-master/war/target/cimi-war-13.10.0-SNAPSHOT]
> > > > > [INFO] Copying webapp resources [/home/afaresse/Bureau/cimi-master/war/src/main/webapp]
> > > > > [INFO] Webapp assembled in [1032 msecs]
> > > > > [INFO] Building war: /home/afaresse/Bureau/cimi-master/war/target/cimi-war-13.10.0-SNAPSHOT.war
> > > > > [INFO] [clojure:run {execution: run-codox}]
> > > > > Erreur : impossible de trouver ou charger la classe principale clojure.main

J'ai ce erreur là et j'ai besoin d'une solution merci

**Comment by loomis** [comment]
The compilation and build work for me, so please include more information:
- What command did you use to do the compilation?
- Are you doing the build with or without the tests? 
- What operating system are you using?
- What versions of tools do you have (specifically java and mvn)?

**Comment by afaresse** [comment]
for command mvn clean install -DNO_DB_TESTS
operating system is ubuntu 12.04
java-6-openjdk
Apache Maven 2.2.1
java vesion 1.6.0-27

Merci pour tout

2013/11/8 Charles (Cal) Loomis notifications@github.com

> The compilation and build work for me, so please include more information:
> - What command did you use to do the compilation?
> - Are you doing the build with or without the tests?
> - What operating system are you using?
> - What versions of tools do you have (specifically java and mvn)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StratusLab/cimi/issues/3#issuecomment-28073957
> .

## 

Abdeljabbar Faresse

Ingénieur en Informatique

95, Route de Suisse 1290 Versoix/Genève

Tél. : +41 76 562 24 71

_faresse1@gmail.com_ abdeljabbar.faresse@etat.ge.ch

**Comment by loomis** [comment]
Maven 2.2.1 is too old.  It treats the test classpath differently and doesn't work correctly for this repository.  I've added a Maven 3.0.4 prerequisite to the main pom.xml file and updated the README.  For Ubuntu, install the 'maven' rather than the 'maven2' package with `apt-get`.

**Comment by afaresse** [comment]
Merci c'est ça l'erreur

Bonne soirée

2013/11/8 Charles (Cal) Loomis notifications@github.com

> Maven 2.2.1 is too old. It treats the test classpath differently and
> doesn't work correctly for this repository. I've added a Maven 3.0.4
> prerequisite to the main pom.xml file and updated the README. For Ubuntu,
> install the 'maven' rather than the 'maven2' package with apt-get.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StratusLab/cimi/issues/3#issuecomment-28088325
> .

## 

Abdeljabbar Faresse

Ingénieur en Informatique

95, Route de Suisse 1290 Versoix/Genève

Tél. : +41 76 562 24 71

_faresse1@gmail.com_ abdeljabbar.faresse@etat.ge.ch

**Comment by afaresse** [comment]
Bonjour,

J'aimerais bien te demander si tu peux m'envoyer ou donner un peu de détail
sur le projet StratusLab/cimi car je vais utiliser ton projet pour faire la
même chose avec CloudStack j'ai besoin d'avoir un peu de détail pour
comprendre la démarche à suivre merci de m'aider

Bonne journée

2013/11/8 Charles (Cal) Loomis notifications@github.com

> The compilation and build work for me, so please include more information:
> - What command did you use to do the compilation?
> - Are you doing the build with or without the tests?
> - What operating system are you using?
> - What versions of tools do you have (specifically java and mvn)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StratusLab/cimi/issues/3#issuecomment-28073957
> .

## 

Abdeljabbar Faresse

Ingénieur en Informatique

95, Route de Suisse 1290 Versoix/Genève

Tél. : +41 76 562 24 71

_faresse1@gmail.com_ abdeljabbar.faresse@etat.ge.ch

**Comment by loomis** [comment]
These issues aren't really adapted to support requests.  It is better to contact me (or the other developers) directly.  I've sent you my email address separately.
